apiVersion: apps/v1
kind: Deployment
metadata:
  name: patient-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: patient-api
  template:
    metadata:
      labels:
        app: patient-api
    spec:
      containers:
        - name: patient-api
          image: anashismail/patient-api:latest
          ports:
            - containerPort: 8000
